# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/decision/decision_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/decision/decision_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.common import robot_id_pb2 as protocols_dot_common_dot_robot__id__pb2
from protocols.common import geometry_pb2 as protocols_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)protocols/decision/decision_service.proto\x12\x12protocols.decision\x1a\x1fprotocols/common/robot_id.proto\x1a\x1fprotocols/common/geometry.proto\"j\n\x08\x44\x65\x63ision\x12.\n\x08\x62\x65havior\x18\x01 \x03(\x0b\x32\x1c.protocols.decision.Behavior\x12.\n\x04plan\x18\x02 \x01(\x0b\x32 .protocols.decision.TacticalPlan\"\x7f\n\x08\x42\x65havior\x12\n\n\x02id\x18\x01 \x01(\r\x12+\n\x08robot_id\x18\x02 \x01(\x0b\x32\x19.protocols.common.RobotId\x12/\n\x06target\x18\x03 \x01(\x0b\x32\x1a.protocols.common.Point2DfH\x00\x88\x01\x01\x42\t\n\x07_target\"z\n\x0cTacticalPlan\x12\x34\n\toffensive\x18\x01 \x01(\x0b\x32!.protocols.decision.OffensivePlan\x12\x34\n\tdefensive\x18\x02 \x01(\x0b\x32!.protocols.decision.DefensivePlan\"\x0f\n\rDefensivePlan\"\x0f\n\rOffensivePlanb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.decision.decision_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DECISION']._serialized_start=131
  _globals['_DECISION']._serialized_end=237
  _globals['_BEHAVIOR']._serialized_start=239
  _globals['_BEHAVIOR']._serialized_end=366
  _globals['_TACTICALPLAN']._serialized_start=368
  _globals['_TACTICALPLAN']._serialized_end=490
  _globals['_DEFENSIVEPLAN']._serialized_start=492
  _globals['_DEFENSIVEPLAN']._serialized_end=507
  _globals['_OFFENSIVEPLAN']._serialized_start=509
  _globals['_OFFENSIVEPLAN']._serialized_end=524
# @@protoc_insertion_point(module_scope)
