#ifndef DECISION_PROCESSING_ENTITIES_BEHAVIOR_STATE_MACHINE_H
#define DECISION_PROCESSING_ENTITIES_BEHAVIOR_STATE_MACHINE_H

class StateMachines {
 public:
  enum class GoalkeeperStateMachines {
    GUARD = 0,
    TAKE_BALL_AWAY = 1,
  };
};

#endif // DECISION_PROCESSING_ENTITIES_BEHAVIOR_STATE_MACHINE_H
