services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/gateway-augusto/gateway-augusto.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    ports:
      - 50051:50051

  perception-ms:
    container_name: perception-ms
    image: robocin/perception-brutus:manual-5907a5
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway

  referee-ms:
    container_name: referee-ms
    image: robocin/referee-daronco:manual-5907a5
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms

  redis-db:
    container_name: redis-db
    image: "redis:latest"

  playback-ms:
    container_name: playback-ms
    build:
      context: .
      dockerfile: playback-ms/playback-caze/playback-caze.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - referee-ms
      - redis-db

  player-bff:
    container_name: player-bff
    build:
      context: .
      dockerfile: player-bff/Dockerfile
      args:
        - SOURCE_DIRECTORY=player-bff
    command: ["./player-bff"]
    ports:
      - 4040:4040
    depends_on:
      - gateway
      - playback-ms

  player-mfe:
    build:
      context: .
      dockerfile: player-mfe/Dockerfile
      args:
        - SOURCE_DIRECTORY=player-mfe
    command: ["-g", "daemon off;"]
    ports:
      - 3031:80
    depends_on:
      - player-bff

  viewer-mfe:
    build:
      context: .
      dockerfile: viewer-mfe/Dockerfile
      args:
        - SOURCE_DIRECTORY=viewer-mfe
    command: ["-g", "daemon off;"]
    ports:
      - 3032:80

  app-shell:
    build:
      context: .
      dockerfile: app-shell/Dockerfile
      args:
        - SOURCE_DIRECTORY=app-shell
    command: ["-g", "daemon off;"]
    ports:
      - 3030:80

volumes:
  .ssl-core:
