version: "3"

services:
  simulator:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    restart: unless-stopped
    container_name: simulator
    environment:
      GEOMETRY: "2020"
      REALISM: "RC2021"

  autoref-tigers:
    image: tigersmannheim/auto-referee:1.2.0
    restart: unless-stopped
    container_name: autoref-tigers
    # Run without UI in active mode
    command: [ "-a" ]
    depends_on:
    - simulator

  gateway:
    build:
      context: .
      dockerfile: gateway/gateway-augusto/Dockerfile
      args:
        - SOURCE_DIRECTORY=gateway/gateway-augusto
    working_dir: /workspaces/gateway/gateway-augusto
    container_name: gateway
    command: ["bin/gateway_main"]
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
      - ./:/app
    depends_on:
    - autoref-tigers

  perception:
    build:
      context: .
      dockerfile: perception-ms/perception-brutus/Dockerfile
      args:
        - SOURCE_DIRECTORY=perception-ms/perception-brutus
    working_dir: /workspaces/perception-ms/perception-brutus
    container_name: perception
    command: ["bin/perception_main"]
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway
