services:
  simulator:
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    restart: unless-stopped
    container_name: simulator
    environment:
      GEOMETRY: "2020"
      REALISM: "RC2021"
    network_mode: "host"

  autoref-tigers:
    image: tigersmannheim/auto-referee:1.2.0
    restart: unless-stopped
    container_name: autoref-tigers
    # Run without UI in active mode
    command:
      - "-a"
      - "-visionAddress"
      - "224.5.23.2:10020"
    network_mode: "host"
    depends_on:
      - simulator

  ssl-game-controller:
    image: robocupssl/ssl-game-controller:3.9.0
    command:
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    restart: unless-stopped
    ports:
      - 8081/tcp
    network_mode: "host"
    depends_on:
      - autoref-tigers

  ssl-vision-client:
    image: robocupssl/ssl-vision-client:1.7.3
    command:
      - "-visionAddress"
      - "224.5.23.2:10020"
    restart: unless-stopped
    ports:
      - 8082/tcp
    network_mode: "host"
    depends_on:
      - ssl-game-controller

  gateway:
    build:
      context: .
      dockerfile: gateway/gateway-augusto/Dockerfile
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
    network_mode: "host"
    depends_on:
      - simulator

  perception-ms:
    build:
      context: .
      dockerfile: perception-ms/perception-brutus/Dockerfile
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
    network_mode: "host"
    depends_on:
      - simulator

  referee-ms:
    build:
      context: .
      dockerfile: referee-ms/referee-daronco/Dockerfile
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
    network_mode: "host"
    depends_on:
      - simulator

networks:
  default:
    name: "host"
    external: true
