services:
  simulator:
    container_name: simulator
    image: roboticserlangen/simulatorcli:commit-6a4e1c06533b
    restart: unless-stopped
    environment:
      GEOMETRY: "2020"
      REALISM: "RC2021"
    logging:
      driver: none

  autoref-tigers:
    container_name: autoref-tigers
    image: tigersmannheim/auto-referee:1.2.0
    restart: unless-stopped
    command:
      - "-a"
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-refereeAddress"
      - "224.5.23.1:11003"
    logging:
      driver: none
    depends_on:
      - simulator

  game-controller:
    container_name: game-controller
    image: robocupssl/ssl-game-controller:3.9.0
    command:
      - "-visionAddress"
      - "224.5.23.2:10020"
      - "-trackerAddress"
      - "224.5.23.2:11010"
      - "-publishAddress"
      - "224.5.23.1:11003"
      - "-address"
      - ":8081"
    restart: unless-stopped
    ports:
      - 8081/tcp
      - 8081:8081
    logging:
      driver: none
    depends_on:
      - autoref-tigers

  ssl-vision-client:
    container_name: ssl-vision-client
    image: robocupssl/ssl-vision-client:1.7.3
    command:
      - "-visionAddress"
      - "224.5.23.2:10020"
    restart: unless-stopped
    ports:
      - 8082/tcp
      - 8082:8082
    logging:
      driver: none
    depends_on:
      - game-controller
    network_mode: host

  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/gateway-augusto/gateway-augusto.Dockerfile
    environment:
      - VISION_PORT=10020
      - GC_PORT=11003
    volumes:
      - .ssl-core:/tmp/.ssl-core
    ports:
      - 50051:50051
    depends_on:
      - simulator

  perception-ms:
    container_name: perception-ms
    build:
      context: .
      dockerfile: perception-ms/perception-brutus/perception-brutus.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway

  referee-ms:
    container_name: referee-ms
    build:
      context: .
      dockerfile: referee-ms/referee-daronco/referee-daronco.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms

  playback-ms:
    container_name: playback-ms
    build:
      context: .
      dockerfile: playback-ms/playback-caze/playback-caze.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - referee-ms
    attach: false


  app-shell:
    build:
      context: .
      dockerfile: app-shell/Dockerfile
      args:
        - SOURCE_DIRECTORY=app-shell
    command: [ "-g", "daemon off;" ]
    ports:
      - 3030:3030

  navigation-ms:
    container_name: navigation-ms
    build:
      context: .
      dockerfile: navigation-ms/navigation-luffy/navigation-luffy.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    attach: true

  decision-ms:
    container_name: decision-ms
    build:
      context: .
      dockerfile: decision-ms/decision-guardiola/decision-guardiola.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms
      - referee-ms
    attach: false

  behavior-ms:
    container_name: behavior-ms
    build:
      context: .
      dockerfile: behavior-ms/behavior-bruxo/behavior-bruxo.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    attach: true
  
  communication-ms:
    container_name: communication-ms
    build:
      context: .
      dockerfile: communication-ms/communication-jaiminho/communication-jaiminho.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway
    network_mode: "host"
    attach: false


volumes:
  .ssl-core:
