services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/gateway-augusto/Dockerfile
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
    ports:
      - 50051:50051

  perception-ms:
    container_name: perception-ms
    build:
      context: .
      dockerfile: perception-ms/perception-brutus/Dockerfile
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - gateway

  referee-ms:
    container_name: referee-ms
    build:
      context: .
      dockerfile: referee-ms/referee-daronco/Dockerfile
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - perception-ms

  playback-ms:
    container_name: playback-ms
    build:
      context: .
      dockerfile: playback-ms/playback-caze/Dockerfile
      args:
        - SOURCE_DIRECTORY=playback-ms/playback-caze
    command: ./playback-ms
    volumes:
      - /tmp/.ssl-core:/tmp/.ssl-core
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis-db
      
  player-bff:
    container_name: player-bff
    build:
      context: .
      dockerfile: player-bff/Dockerfile
      args:
        - SOURCE_DIRECTORY=player-bff
    command: ["./player-bff"]
    ports:
      - 4040:4040
    depends_on:
      - gateway
      - playback-ms
      
  redis-db:
    container_name: redis-db
    image: "redis:latest"
