services:
  gateway:
    container_name: gateway
    build:
      context: .
      dockerfile: gateway/gateway-augusto/gateway-augusto.Dockerfile
    environment:
      - VISION_PORT=10006
      - GC_PORT=10003
      - INTERCEPT=true
      - WAIT_PACKAGES=1000
    volumes:
      - .ssl-core:/tmp/.ssl-core
    network_mode: host

  perception-ms:
    container_name: perception-ms
    image: robocin/perception-brutus:manual-c7208b
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - gateway
    network_mode: host

  referee-ms:
    container_name: referee-ms
    image: robocin/referee-daronco:manual-419128
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - perception-ms
    network_mode: host

  playback-db:
    container_name: playback-db
    image: "redis:latest"
    network_mode: host

  playback-ms:
    container_name: playback-ms
    build:
      context: .
      dockerfile: playback-ms/playback-caze/playback-caze.Dockerfile
    volumes:
      - .ssl-core:/tmp/.ssl-core
    depends_on:
      - referee-ms
      - playback-db
    network_mode: host
    extra_hosts:
      - "playback-db:127.0.0.1"

volumes:
  .ssl-core: