services:
  metrics-db:
    container_name: metrics-db
    image: influxdb:2
    # user: 1000:1000
    # volumes:
    #   - .influxdb/data:/var/lib/influxdb2
    #   - .influxdb/config:/etc/influxdb2
    ports:
      - 8086:8086
    network_mode: "host"

  grafana:
    container_name: grafana
    image: grafana/grafana
    # user: 1000:1000
    # volumes:
    #   - .grafana/data:/var/lib/grafana
    #   - .grafana/config:/etc/grafana/provisioning
    ports:
      - 3000:3000
    network_mode: "host"

networks:
  default:
    name: "host"
    external: true
