version: '3'

services:
  service-0:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "0"]
    volumes:
      - /tmp:/tmp
    
  service-1:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "1"]
    volumes:
      - /tmp:/tmp

  service-2:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "2"]
    volumes:
      - /tmp:/tmp

  service-3:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "3"]
    volumes:
      - /tmp:/tmp

  service-4:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "4"]
    volumes:
      - /tmp:/tmp

  service-5:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "5"]
    volumes:
      - /tmp:/tmp
