version: '3'

services:
  service-0:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "0"]
    volumes:
      - /tmp:/tmp

  service-1:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "1"]
    volumes:
      - /tmp:/tmp
    depends_on:
      - service-0

  service-2:
    build:
      context: .
      dockerfile: service.Dockerfile
    command: ["bin/vision", "2"]
    volumes:
      - /tmp:/tmp
    depends_on:
      - service-1
