# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/feedback.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/feedback.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.common import robot_id_pb2 as protocols_dot_common_dot_robot__id__pb2
from protocols.common import robot_pose_pb2 as protocols_dot_common_dot_robot__pose__pb2
from protocols.common import robot_kick_pb2 as protocols_dot_common_dot_robot__kick__pb2
from protocols.common import robot_velocity_pb2 as protocols_dot_common_dot_robot__velocity__pb2
from protocols.common import robot_motor_pb2 as protocols_dot_common_dot_robot__motor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotocols/common/feedback.proto\x12\x10protocols.common\x1a\x1fprotocols/common/robot_id.proto\x1a!protocols/common/robot_pose.proto\x1a!protocols/common/robot_kick.proto\x1a%protocols/common/robot_velocity.proto\x1a\"protocols/common/robot_motor.proto\"\xdc\x02\n\x08\x46\x65\x65\x64\x62\x61\x63k\x12\x37\n\ttelemetry\x18\x01 \x01(\x0b\x32$.protocols.common.Feedback.Telemetry\x12.\n\x04pose\x18\x02 \x01(\x0b\x32\x1b.protocols.common.RobotPoseH\x00\x88\x01\x01\x1a\xdd\x01\n\tTelemetry\x12+\n\x08robot_id\x18\x01 \x01(\x0b\x32\x19.protocols.common.RobotId\x12\x37\n\x0erobot_velocity\x18\x02 \x01(\x0b\x32\x1f.protocols.common.RobotVelocity\x12\x31\n\x0brobot_motor\x18\x03 \x01(\x0b\x32\x1c.protocols.common.RobotMotor\x12\x37\n\tkick_info\x18\x04 \x01(\x0b\x32$.protocols.common.RobotKick.KickInfoB\x07\n\x05_poseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.feedback_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FEEDBACK']._serialized_start=232
  _globals['_FEEDBACK']._serialized_end=580
  _globals['_FEEDBACK_TELEMETRY']._serialized_start=350
  _globals['_FEEDBACK_TELEMETRY']._serialized_end=571
# @@protoc_insertion_point(module_scope)
