# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/game_stage.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/game_stage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protocols/common/game_stage.proto\x12\x10protocols.common*\x8b\x04\n\tGameStage\x12\x1a\n\x16GAME_STAGE_UNSPECIFIED\x10\x00\x12$\n GAME_STAGE_NORMAL_FIRST_HALF_PRE\x10\x01\x12 \n\x1cGAME_STAGE_NORMAL_FIRST_HALF\x10\x02\x12\x1f\n\x1bGAME_STAGE_NORMAL_HALF_TIME\x10\x03\x12%\n!GAME_STAGE_NORMAL_SECOND_HALF_PRE\x10\x04\x12!\n\x1dGAME_STAGE_NORMAL_SECOND_HALF\x10\x05\x12\x1f\n\x1bGAME_STAGE_EXTRA_TIME_BREAK\x10\x06\x12#\n\x1fGAME_STAGE_EXTRA_FIRST_HALF_PRE\x10\x07\x12\x1f\n\x1bGAME_STAGE_EXTRA_FIRST_HALF\x10\x08\x12\x1e\n\x1aGAME_STAGE_EXTRA_HALF_TIME\x10\t\x12$\n GAME_STAGE_EXTRA_SECOND_HALF_PRE\x10\n\x12 \n\x1cGAME_STAGE_EXTRA_SECOND_HALF\x10\x0b\x12%\n!GAME_STAGE_PENALTY_SHOOTOUT_BREAK\x10\x0c\x12\x1f\n\x1bGAME_STAGE_PENALTY_SHOOTOUT\x10\r\x12\x18\n\x14GAME_STAGE_POST_GAME\x10\x0e\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.game_stage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GAMESTAGE']._serialized_start=56
  _globals['_GAMESTAGE']._serialized_end=579
# @@protoc_insertion_point(module_scope)
