# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/peripheral_actuation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/peripheral_actuation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.common import robot_kick_pb2 as protocols_dot_common_dot_robot__kick__pb2
from protocols.common import robot_dribbler_pb2 as protocols_dot_common_dot_robot__dribbler__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+protocols/common/peripheral_actuation.proto\x12\x10protocols.common\x1a!protocols/common/robot_kick.proto\x1a%protocols/common/robot_dribbler.proto\"\x8d\x01\n\x13PeripheralActuation\x12=\n\x0ckick_command\x18\x01 \x01(\x0b\x32\'.protocols.common.RobotKick.KickCommand\x12\x37\n\x0erobot_dribbler\x18\x02 \x01(\x0b\x32\x1f.protocols.common.RobotDribblerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.peripheral_actuation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PERIPHERALACTUATION']._serialized_start=140
  _globals['_PERIPHERALACTUATION']._serialized_end=281
# @@protoc_insertion_point(module_scope)
