# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/robot_motor.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/robot_motor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"protocols/common/robot_motor.proto\x12\x10protocols.common\"\x86\x01\n\nRobotMotor\x12\x31\n\x05motor\x18\x04 \x03(\x0b\x32\".protocols.common.RobotMotor.Motor\x1a\x45\n\x05Motor\x12\x10\n\x08motor_id\x18\x01 \x01(\r\x12\x13\n\x0bmotor_speed\x18\x02 \x01(\x02\x12\x15\n\rmotor_current\x18\x03 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.robot_motor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTMOTOR']._serialized_start=57
  _globals['_ROBOTMOTOR']._serialized_end=191
  _globals['_ROBOTMOTOR_MOTOR']._serialized_start=122
  _globals['_ROBOTMOTOR_MOTOR']._serialized_end=191
# @@protoc_insertion_point(module_scope)
