# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/robot_pose.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/robot_pose.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.common import geometry_pb2 as protocols_dot_common_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protocols/common/robot_pose.proto\x12\x10protocols.common\x1a\x1fprotocols/common/geometry.proto\"N\n\tRobotPose\x12,\n\x08position\x18\x01 \x01(\x0b\x32\x1a.protocols.common.Point2Df\x12\x13\n\x0borientation\x18\x02 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.robot_pose_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTPOSE']._serialized_start=88
  _globals['_ROBOTPOSE']._serialized_end=166
# @@protoc_insertion_point(module_scope)
