# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/robot_id.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/robot_id.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotocols/common/robot_id.proto\x12\x10protocols.common\"\x9a\x01\n\x07RobotId\x12\x33\n\x05\x63olor\x18\x01 \x01(\x0e\x32\x1f.protocols.common.RobotId.ColorH\x00\x88\x01\x01\x12\x0e\n\x06number\x18\x02 \x01(\r\"@\n\x05\x43olor\x12\x15\n\x11\x43OLOR_UNSPECIFIED\x10\x00\x12\x10\n\x0c\x43OLOR_YELLOW\x10\x01\x12\x0e\n\nCOLOR_BLUE\x10\x02\x42\x08\n\x06_colorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.robot_id_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTID']._serialized_start=54
  _globals['_ROBOTID']._serialized_end=208
  _globals['_ROBOTID_COLOR']._serialized_start=134
  _globals['_ROBOTID_COLOR']._serialized_end=198
# @@protoc_insertion_point(module_scope)
