# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/robot_dribbler.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/robot_dribbler.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%protocols/common/robot_dribbler.proto\x12\x10protocols.common\"\xc9\x02\n\rRobotDribbler\x12K\n\x10\x64ribbler_command\x18\x01 \x01(\x0b\x32/.protocols.common.RobotDribbler.DribblerCommandH\x00\x12\x45\n\rdribbler_info\x18\x02 \x01(\x0b\x32,.protocols.common.RobotDribbler.DribblerInfoH\x00\x1a<\n\x0f\x44ribblerCommand\x12\x16\n\x0e\x64ribbler_speed\x18\x01 \x01(\x01\x12\x11\n\tis_active\x18\x02 \x01(\x08\x1aZ\n\x0c\x44ribblerInfo\x12\x16\n\x0e\x64ribbler_speed\x18\x01 \x01(\x01\x12\x18\n\x10\x64ribbler_current\x18\x02 \x01(\x01\x12\x18\n\x10is_ball_detected\x18\x03 \x01(\x08\x42\n\n\x08\x64ribblerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.robot_dribbler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTDRIBBLER']._serialized_start=60
  _globals['_ROBOTDRIBBLER']._serialized_end=389
  _globals['_ROBOTDRIBBLER_DRIBBLERCOMMAND']._serialized_start=225
  _globals['_ROBOTDRIBBLER_DRIBBLERCOMMAND']._serialized_end=285
  _globals['_ROBOTDRIBBLER_DRIBBLERINFO']._serialized_start=287
  _globals['_ROBOTDRIBBLER_DRIBBLERINFO']._serialized_end=377
# @@protoc_insertion_point(module_scope)
