# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/common/robot_kick.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/common/robot_kick.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!protocols/common/robot_kick.proto\x12\x10protocols.common\"\xc8\x02\n\tRobotKick\x12?\n\x0ckick_command\x18\x01 \x01(\x0b\x32\'.protocols.common.RobotKick.KickCommandH\x00\x12\x39\n\tkick_info\x18\x02 \x01(\x0b\x32$.protocols.common.RobotKick.KickInfoH\x00\x1aw\n\x0bKickCommand\x12\x15\n\rkick_strength\x18\x01 \x01(\x01\x12\x10\n\x08is_front\x18\x02 \x01(\x08\x12\x0f\n\x07is_chip\x18\x03 \x01(\x08\x12\x18\n\x10\x63harge_capacitor\x18\x04 \x01(\x08\x12\x14\n\x0cis_bypass_ir\x18\x05 \x01(\x08\x1a>\n\x08KickInfo\x12\x18\n\x10\x63\x61pacitor_charge\x18\x01 \x01(\x01\x12\x18\n\x10is_ball_detected\x18\x02 \x01(\x08\x42\x06\n\x04kickb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.common.robot_kick_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ROBOTKICK']._serialized_start=56
  _globals['_ROBOTKICK']._serialized_end=384
  _globals['_ROBOTKICK_KICKCOMMAND']._serialized_start=193
  _globals['_ROBOTKICK_KICKCOMMAND']._serialized_end=312
  _globals['_ROBOTKICK_KICKINFO']._serialized_start=314
  _globals['_ROBOTKICK_KICKINFO']._serialized_end=376
# @@protoc_insertion_point(module_scope)
