# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/playback/field.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/playback/field.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eprotocols/playback/field.proto\x12\x12protocols.playback\"\xc3\x01\n\x05\x46ield\x12\x0e\n\x06length\x18\x01 \x01(\x02\x12\r\n\x05width\x18\x02 \x01(\x02\x12\x12\n\ngoal_depth\x18\x03 \x01(\x02\x12\x12\n\ngoal_width\x18\x04 \x01(\x02\x12\x1a\n\x12penalty_area_depth\x18\x05 \x01(\x02\x12\x1a\n\x12penalty_area_width\x18\x06 \x01(\x02\x12\x16\n\x0e\x62oundary_width\x18\x07 \x01(\x02\x12#\n\x1bgoal_center_to_penalty_mark\x18\x08 \x01(\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.playback.field_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FIELD']._serialized_start=55
  _globals['_FIELD']._serialized_end=250
# @@protoc_insertion_point(module_scope)
