# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/playback/sample.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/playback/sample.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protocols.playback import detection_pb2 as protocols_dot_playback_dot_detection__pb2
from protocols.playback import field_pb2 as protocols_dot_playback_dot_field__pb2
from protocols.playback import game_status_pb2 as protocols_dot_playback_dot_game__status__pb2
from protocols.playback import raw_detection_pb2 as protocols_dot_playback_dot_raw__detection__pb2
from protocols.playback import tracked_detection_pb2 as protocols_dot_playback_dot_tracked__detection__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fprotocols/playback/sample.proto\x12\x12protocols.playback\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"protocols/playback/detection.proto\x1a\x1eprotocols/playback/field.proto\x1a$protocols/playback/game_status.proto\x1a&protocols/playback/raw_detection.proto\x1a*protocols/playback/tracked_detection.proto\"\xe0\x03\n\x06Sample\x12\x33\n\x0f\x66irst_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12-\n\x05\x66ield\x18\x03 \x01(\x0b\x32\x19.protocols.playback.FieldH\x00\x88\x01\x01\x12\x35\n\tdetection\x18\x04 \x01(\x0b\x32\x1d.protocols.playback.DetectionH\x01\x88\x01\x01\x12\x38\n\x0bgame_status\x18\x05 \x01(\x0b\x32\x1e.protocols.playback.GameStatusH\x02\x88\x01\x01\x12<\n\rraw_detection\x18\x06 \x01(\x0b\x32 .protocols.playback.RawDetectionH\x03\x88\x01\x01\x12\x44\n\x11tracked_detection\x18\x07 \x01(\x0b\x32$.protocols.playback.TrackedDetectionH\x04\x88\x01\x01\x42\x08\n\x06_fieldB\x0c\n\n_detectionB\x0e\n\x0c_game_statusB\x10\n\x0e_raw_detectionB\x14\n\x12_tracked_detectionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.playback.sample_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SAMPLE']._serialized_start=279
  _globals['_SAMPLE']._serialized_end=759
# @@protoc_insertion_point(module_scope)
