# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/behavior/behavior_unification.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/behavior/behavior_unification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.common import peripheral_actuation_pb2 as protocols_dot_common_dot_peripheral__actuation__pb2
from protocols.navigation import motion_pb2 as protocols_dot_navigation_dot_motion__pb2
from protocols.navigation import navigation_pb2 as protocols_dot_navigation_dot_navigation__pb2
from protocols.navigation import planning_pb2 as protocols_dot_navigation_dot_planning__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-protocols/behavior/behavior_unification.proto\x12\x1eprotocols.behavior.unification\x1a+protocols/common/peripheral_actuation.proto\x1a!protocols/navigation/motion.proto\x1a%protocols/navigation/navigation.proto\x1a#protocols/navigation/planning.proto\"\xba\x01\n\x08\x42\x65havior\x12\x38\n\x06motion\x18\x01 \x01(\x0b\x32&.protocols.behavior.unification.MotionH\x00\x12\x32\n\x08planning\x18\x02 \x01(\x0b\x32\x1e.protocols.navigation.PlanningH\x00\x12\x36\n\nnavigation\x18\x03 \x01(\x0b\x32 .protocols.navigation.NavigationH\x00\x42\x08\n\x06output\"\xe1\x02\n\x06Motion\x12\x36\n\x0bgo_to_point\x18\x01 \x01(\x0b\x32\x1f.protocols.navigation.GoToPointH\x00\x12T\n\x1bgo_to_point_with_trajectory\x18\x02 \x01(\x0b\x32-.protocols.navigation.GoToPointWithTrajectoryH\x00\x12>\n\x0frotate_in_point\x18\x03 \x01(\x0b\x32#.protocols.navigation.RotateInPointH\x00\x12<\n\x0erotate_on_self\x18\x04 \x01(\x0b\x32\".protocols.navigation.RotateOnSelfH\x00\x12\x43\n\x14peripheral_actuation\x18\x05 \x01(\x0b\x32%.protocols.common.PeripheralActuationB\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.behavior.behavior_unification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BEHAVIOR']._serialized_start=238
  _globals['_BEHAVIOR']._serialized_end=424
  _globals['_MOTION']._serialized_start=427
  _globals['_MOTION']._serialized_end=780
# @@protoc_insertion_point(module_scope)
