# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/behavior/behavior_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/behavior/behavior_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.common import geometry_pb2 as protocols_dot_common_dot_geometry__pb2
from protocols.common import robot_id_pb2 as protocols_dot_common_dot_robot__id__pb2
from protocols.common import peripheral_actuation_pb2 as protocols_dot_common_dot_peripheral__actuation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)protocols/behavior/behavior_service.proto\x12\x12protocols.behavior\x1a\x1fprotocols/common/geometry.proto\x1a\x1fprotocols/common/robot_id.proto\x1a+protocols/common/peripheral_actuation.proto\"\xab\x01\n\x06Motion\x12*\n\x06target\x18\x01 \x01(\x0b\x32\x1a.protocols.behavior.Target\x12\x30\n\tobstacles\x18\x02 \x01(\x0b\x32\x1d.protocols.behavior.Obstacles\x12\x43\n\x14peripheral_actuation\x18\x03 \x01(\x0b\x32%.protocols.common.PeripheralActuation\"\x87\x01\n\x06Target\x12,\n\x08position\x18\x01 \x01(\x0b\x32\x1a.protocols.common.Point2Df\x12\r\n\x05\x61ngle\x18\x02 \x01(\x02\x12,\n\x08velocity\x18\x03 \x01(\x0b\x32\x1a.protocols.common.Point2DfJ\x04\x08\x04\x10\x05R\x0c\x61\x63\x63\x65leration\"\xc4\x01\n\tObstacles\x12\x0c\n\x04\x62\x61ll\x18\x01 \x01(\x08\x12)\n\x06robots\x18\x02 \x03(\x0b\x32\x19.protocols.common.RobotId\x12\x19\n\x11left_penalty_area\x18\x03 \x01(\x08\x12\x1a\n\x12right_penalty_area\x18\x04 \x01(\x08\x12\x16\n\x0e\x66ield_boundary\x18\x05 \x01(\x08\x12\x16\n\x0eleft_goal_post\x18\x06 \x01(\x08\x12\x17\n\x0fright_goal_post\x18\x07 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.behavior.behavior_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOTION']._serialized_start=177
  _globals['_MOTION']._serialized_end=348
  _globals['_TARGET']._serialized_start=351
  _globals['_TARGET']._serialized_end=486
  _globals['_OBSTACLES']._serialized_start=489
  _globals['_OBSTACLES']._serialized_end=685
# @@protoc_insertion_point(module_scope)
