# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protocols.gateway import gateway_service_pb2 as protocols_dot_gateway_dot_gateway__service__pb2

GRPC_GENERATED_VERSION = '1.66.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protocols/gateway/gateway_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveLivestream = channel.stream_stream(
                '/protocols.gateway.GatewayService/ReceiveLivestream',
                request_serializer=protocols_dot_gateway_dot_gateway__service__pb2.ReceiveLivestreamRequest.SerializeToString,
                response_deserializer=protocols_dot_gateway_dot_gateway__service__pb2.ReceiveLivestreamResponse.FromString,
                _registered_method=True)
        self.GetGameEvents = channel.unary_unary(
                '/protocols.gateway.GatewayService/GetGameEvents',
                request_serializer=protocols_dot_gateway_dot_gateway__service__pb2.GetGameEventsRequest.SerializeToString,
                response_deserializer=protocols_dot_gateway_dot_gateway__service__pb2.GetGameEventsResponse.FromString,
                _registered_method=True)
        self.GetReplayChunk = channel.unary_unary(
                '/protocols.gateway.GatewayService/GetReplayChunk',
                request_serializer=protocols_dot_gateway_dot_gateway__service__pb2.GetReplayChunkRequest.SerializeToString,
                response_deserializer=protocols_dot_gateway_dot_gateway__service__pb2.GetReplayChunkResponse.FromString,
                _registered_method=True)


class GatewayServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReceiveLivestream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGameEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetReplayChunk(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveLivestream': grpc.stream_stream_rpc_method_handler(
                    servicer.ReceiveLivestream,
                    request_deserializer=protocols_dot_gateway_dot_gateway__service__pb2.ReceiveLivestreamRequest.FromString,
                    response_serializer=protocols_dot_gateway_dot_gateway__service__pb2.ReceiveLivestreamResponse.SerializeToString,
            ),
            'GetGameEvents': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGameEvents,
                    request_deserializer=protocols_dot_gateway_dot_gateway__service__pb2.GetGameEventsRequest.FromString,
                    response_serializer=protocols_dot_gateway_dot_gateway__service__pb2.GetGameEventsResponse.SerializeToString,
            ),
            'GetReplayChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.GetReplayChunk,
                    request_deserializer=protocols_dot_gateway_dot_gateway__service__pb2.GetReplayChunkRequest.FromString,
                    response_serializer=protocols_dot_gateway_dot_gateway__service__pb2.GetReplayChunkResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protocols.gateway.GatewayService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('protocols.gateway.GatewayService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GatewayService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReceiveLivestream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/protocols.gateway.GatewayService/ReceiveLivestream',
            protocols_dot_gateway_dot_gateway__service__pb2.ReceiveLivestreamRequest.SerializeToString,
            protocols_dot_gateway_dot_gateway__service__pb2.ReceiveLivestreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGameEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocols.gateway.GatewayService/GetGameEvents',
            protocols_dot_gateway_dot_gateway__service__pb2.GetGameEventsRequest.SerializeToString,
            protocols_dot_gateway_dot_gateway__service__pb2.GetGameEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetReplayChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/protocols.gateway.GatewayService/GetReplayChunk',
            protocols_dot_gateway_dot_gateway__service__pb2.GetReplayChunkRequest.SerializeToString,
            protocols_dot_gateway_dot_gateway__service__pb2.GetReplayChunkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
