# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/gateway/gateway_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/gateway/gateway_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protocols.common import game_event_pb2 as protocols_dot_common_dot_game__event__pb2
from protocols.playback import sample_pb2 as protocols_dot_playback_dot_sample__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'protocols/gateway/gateway_service.proto\x12\x11protocols.gateway\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!protocols/common/game_event.proto\x1a\x1fprotocols/playback/sample.proto\"\x1a\n\x18ReceiveLivestreamRequest\"G\n\x19ReceiveLivestreamResponse\x12*\n\x06sample\x18\x01 \x01(\x0b\x32\x1a.protocols.playback.Sample\"\x16\n\x14GetGameEventsRequest\"I\n\x15GetGameEventsResponse\x12\x30\n\x0bgame_events\x18\x01 \x03(\x0b\x32\x1b.protocols.common.GameEvent\"L\n\x15GetReplayChunkRequest\x12\x33\n\x0fstart_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"y\n\x16GetReplayChunkResponse\x12\x32\n\x0elast_timestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12+\n\x07samples\x18\x02 \x03(\x0b\x32\x1a.protocols.playback.Sample2\xcf\x02\n\x0eGatewayService\x12r\n\x11ReceiveLivestream\x12+.protocols.gateway.ReceiveLivestreamRequest\x1a,.protocols.gateway.ReceiveLivestreamResponse(\x01\x30\x01\x12\x62\n\rGetGameEvents\x12\'.protocols.gateway.GetGameEventsRequest\x1a(.protocols.gateway.GetGameEventsResponse\x12\x65\n\x0eGetReplayChunk\x12(.protocols.gateway.GetReplayChunkRequest\x1a).protocols.gateway.GetReplayChunkResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.gateway.gateway_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_RECEIVELIVESTREAMREQUEST']._serialized_start=163
  _globals['_RECEIVELIVESTREAMREQUEST']._serialized_end=189
  _globals['_RECEIVELIVESTREAMRESPONSE']._serialized_start=191
  _globals['_RECEIVELIVESTREAMRESPONSE']._serialized_end=262
  _globals['_GETGAMEEVENTSREQUEST']._serialized_start=264
  _globals['_GETGAMEEVENTSREQUEST']._serialized_end=286
  _globals['_GETGAMEEVENTSRESPONSE']._serialized_start=288
  _globals['_GETGAMEEVENTSRESPONSE']._serialized_end=361
  _globals['_GETREPLAYCHUNKREQUEST']._serialized_start=363
  _globals['_GETREPLAYCHUNKREQUEST']._serialized_end=439
  _globals['_GETREPLAYCHUNKRESPONSE']._serialized_start=441
  _globals['_GETREPLAYCHUNKRESPONSE']._serialized_end=562
  _globals['_GATEWAYSERVICE']._serialized_start=565
  _globals['_GATEWAYSERVICE']._serialized_end=900
# @@protoc_insertion_point(module_scope)
