# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/navigation/navigation.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/navigation/navigation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from protocols.common import geometry_pb2 as protocols_dot_common_dot_geometry__pb2
from protocols.common import robot_pose_pb2 as protocols_dot_common_dot_robot__pose__pb2
from protocols.navigation import motion_pb2 as protocols_dot_navigation_dot_motion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n%protocols/navigation/navigation.proto\x12\x14protocols.navigation\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1fprotocols/common/geometry.proto\x1a!protocols/common/robot_pose.proto\x1a!protocols/navigation/motion.proto\"\xf7\x03\n\nNavigation\x12\n\n\x02id\x18\x01 \x01(\r\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x18\n\x10\x66orward_velocity\x18\x03 \x01(\x01\x12\x15\n\rleft_velocity\x18\x04 \x01(\x01\x12\x18\n\x10\x61ngular_velocity\x18\x05 \x01(\x01\x12\x16\n\x0e\x63ustom_command\x18\x06 \x01(\r\x12\x17\n\x0fsequence_number\x18\x07 \x01(\r\x12\x41\n\x1doutput_global_linear_velocity\x18\x08 \x01(\x0b\x32\x1a.protocols.common.Point2Df\x12\x36\n\x0bgo_to_point\x18\t \x01(\x0b\x32\x1f.protocols.navigation.GoToPointH\x00\x12>\n\x0frotate_in_point\x18\n \x01(\x0b\x32#.protocols.navigation.RotateInPointH\x00\x12<\n\x0erotate_on_self\x18\x0b \x01(\x0b\x32\".protocols.navigation.RotateOnSelfH\x00\x12/\n\nrobot_pose\x18\x0c \x01(\x0b\x32\x1b.protocols.common.RobotPoseB\x08\n\x06motionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.navigation.navigation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NAVIGATION']._serialized_start=200
  _globals['_NAVIGATION']._serialized_end=703
# @@protoc_insertion_point(module_scope)
