# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protocols/navigation/planning.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protocols/navigation/planning.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from protocols.navigation import motion_pb2 as protocols_dot_navigation_dot_motion__pb2
from protocols.common import peripheral_actuation_pb2 as protocols_dot_common_dot_peripheral__actuation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#protocols/navigation/planning.proto\x12\x14protocols.navigation\x1a!protocols/navigation/motion.proto\x1a+protocols/common/peripheral_actuation.proto\"\xd0\x02\n\x08Planning\x12\x41\n\x10\x64iscretized_path\x18\x01 \x01(\x0b\x32%.protocols.navigation.DiscretizedPathH\x00\x12\x36\n\x0bgo_to_point\x18\x02 \x01(\x0b\x32\x1f.protocols.navigation.GoToPointH\x00\x12>\n\x0frotate_in_point\x18\x03 \x01(\x0b\x32#.protocols.navigation.RotateInPointH\x00\x12<\n\x0erotate_on_self\x18\x04 \x01(\x0b\x32\".protocols.navigation.RotateOnSelfH\x00\x12\x43\n\x14peripheral_actuation\x18\x05 \x01(\x0b\x32%.protocols.common.PeripheralActuationB\x06\n\x04typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protocols.navigation.planning_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PLANNING']._serialized_start=142
  _globals['_PLANNING']._serialized_end=478
# @@protoc_insertion_point(module_scope)
