name: "C/C++: clang-format"
on:
  pull_request:
    paths:
      [
        "**.h",
        "**.c",
        "**.hh",
        "**.cc",
        '**.h\+\+',
        '**.c\+\+',
        "**.hxx",
        "**.cxx",
        "**.H",
        "**.C",
        "**.hpp",
        "**.cpp",
        "**.ixx",
        "**.cppm",
      ]
  push:
    branches:
      - main
    paths:
      [
        "**.h",
        "**.c",
        "**.hh",
        "**.cc",
        '**.h\+\+',
        '**.c\+\+',
        "**.hxx",
        "**.cxx",
        "**.H",
        "**.C",
        "**.hpp",
        "**.cpp",
        "**.ixx",
        "**.cppm",
      ]
  workflow_dispatch:

jobs:
  clang_format:
    runs-on: ubuntu-latest
    container: robocin/ssl-core-cpp-base:latest
    steps:
      - uses: actions/checkout@v4
      - uses: cpp-linter/cpp-linter-action@v2
        with:
          extensions: "h,c,hh,cc,h++,c++,hxx,cxx,H,C,hpp,cpp,ixx,cppm"
          version: '' # platform's default installed version
          style: 'file'
          tidy-checks: '-*' # disabled
